import turtle
s = turtle.Screen()
t = turtle.Turtle()
s.bgcolor("cadetblue3")
t.hideturtle()
t.speed(0)
#t.screen.bgpic("bg color for turtle tutorial")
t.color("black")
t.penup()
t.begin_fill()
t.fillcolor("white")
t.goto(-250,-150)
t.pendown()
t.forward(500)
t.setheading(90)
t.forward(300)
t.setheading(180)
t.forward(500)
t.setheading(270)
t.forward(300)
t.end_fill()
t.penup()
t.goto(0,0)
t.pendown()
t.color("black")
t.penup()
t.goto(-80,-10)
t.pendown()
t.begin_fill()
t.fillcolor("red")
t.circle(80)
t.end_fill()
s.exitonclick()